
services:
    shell:
        image: ubuntu_cxx_shell_2204 
        container_name: ubuntu_cxx_shell_2204
        build: 
            context: .
            target: ubuntu_cxx_shell_2204
            dockerfile: ./Dockerfile
        tty: true
        stdin_open: true
        command: bash
        volumes:
          - ./:/home/app_user/app/
